"""Held-out calibration fitness evidence and promotion-gate contracts."""

from specsafe.heldout_calibration.evaluator import (
    HeldOutCalibrationFitnessError,
    HeldOutCalibrationReportPersistenceError,
    evaluate_heldout_calibration_fitness,
    write_heldout_calibration_fitness_report,
)
from specsafe.heldout_calibration.models import (
    AdaptivePolicyResearchEligibility,
    CalibrationPromotionDecision,
    HeldOutCalibrationBin,
    HeldOutCalibrationFitnessProtocol,
    HeldOutCalibrationFitnessResult,
    HeldOutCalibrationFitnessStatus,
    HeldOutFitnessErrorCode,
    ProbabilityFitnessMetrics,
    RuntimeControlEligibility,
)
from specsafe.heldout_calibration.v3_final_assessment import (
    DEFAULT_V3_FINAL_HELDOUT_CALIBRATION_ASSESSMENT_PROTOCOL,
    V3FinalAdaptivePolicyResearchEligibility,
    V3FinalHeldOutCalibrationAssessmentError,
    V3FinalHeldOutCalibrationAssessmentErrorCode,
    V3FinalHeldOutCalibrationAssessmentProtocol,
    V3FinalHeldOutCalibrationAssessmentResult,
    V3FinalHeldOutCalibrationAssessmentStatus,
    V3FinalHeldOutCalibrationBin,
    V3FinalPositionCalibrationMetrics,
    V3FinalProbabilityMetrics,
    evaluate_v3_final_heldout_calibration,
    run_v3_final_heldout_calibration_assessment_once,
    write_v3_final_heldout_calibration_assessment,
)

__all__ = [
    "AdaptivePolicyResearchEligibility",
    "CalibrationPromotionDecision",
    "DEFAULT_V3_FINAL_HELDOUT_CALIBRATION_ASSESSMENT_PROTOCOL",
    "HeldOutCalibrationBin",
    "HeldOutCalibrationFitnessError",
    "HeldOutCalibrationFitnessProtocol",
    "HeldOutCalibrationFitnessResult",
    "HeldOutCalibrationFitnessStatus",
    "HeldOutCalibrationReportPersistenceError",
    "HeldOutFitnessErrorCode",
    "ProbabilityFitnessMetrics",
    "RuntimeControlEligibility",
    "V3FinalAdaptivePolicyResearchEligibility",
    "V3FinalHeldOutCalibrationAssessmentError",
    "V3FinalHeldOutCalibrationAssessmentErrorCode",
    "V3FinalHeldOutCalibrationAssessmentProtocol",
    "V3FinalHeldOutCalibrationAssessmentResult",
    "V3FinalHeldOutCalibrationAssessmentStatus",
    "V3FinalHeldOutCalibrationBin",
    "V3FinalPositionCalibrationMetrics",
    "V3FinalProbabilityMetrics",
    "evaluate_heldout_calibration_fitness",
    "evaluate_v3_final_heldout_calibration",
    "run_v3_final_heldout_calibration_assessment_once",
    "write_heldout_calibration_fitness_report",
    "write_v3_final_heldout_calibration_assessment",
]
